--TABLE
ALTER SESSION SET current_schema = HR;
CREATE TABLE EMISOR2 
   (    
    ID NUMBER,
    IDFK NUMBER, 
    ESTADO VARCHAR2(100 BYTE) DEFAULT NULL,
    FECHA DATE DEFAULT NULL
   ) ;

--INDEX
CREATE UNIQUE INDEX SYS_C006981 ON EMISOR2 (ID);
ALTER TABLE EMISOR2 ADD PRIMARY KEY (ID) ENABLE;
ALTER TABLE EMISOR2 MODIFY (ID NOT NULL ENABLE);
ALTER TABLE EMISOR2 ADD FOREIGN KEY (IDFK) REFERENCES HR.EMISOR(ID);

--SEQUENCE
CREATE SEQUENCE  EMISOR2_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

-- TRIGGERS 
create or replace TRIGGER EMISOR2_TRG 
BEFORE INSERT ON EMISOR2
FOR EACH ROW 
BEGIN
<<COLUMN_SEQUENCES>>
BEGIN
IF INSERTING THEN
SELECT EMISOR2_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
END IF;
END COLUMN_SEQUENCES;
END;

CREATE OR REPLACE TRIGGER RECEPTOR_DATE_TRG
BEFORE INSERT ON EMISOR2
FOR EACH ROW
BEGIN	
    :NEW.FECHA := SYSDATE;
END;

INSERT INTO HR.RECEPTOR (EVENTO, FECHA)
SELECT e.EVENTO, e.FECHA 
FROM HR.EMISOR e
WHERE e.EVENTO = 'REALIZAR' AND EXISTS (SELECT e2.IDFK, e2.ESTADO 
						                FROM HR.EMISOR2 e2
						                WHERE e2.ESTADO = 'PREPARADO' AND e2.IDFK = e.ID)

						                
						                
						                
						                
ALTER TABLE EMISOR ADD SALDO NUMBER;
ALTER TABLE EMISOR2 ADD SALDO NUMBER;
ALTER TABLE RECEPTOR ADD SALDO NUMBER;


INSERT INTO HR.RECEPTOR (EVENTO, FECHA, SALDO)
SELECT e.EVENTO, e.FECHA 
FROM HR.EMISOR e
WHERE e.EVENTO = 'REALIZAR' AND EXISTS (SELECT e2.IDFK, e2.ESTADO 
										FROM HR.EMISOR2 e2
										WHERE e2.ESTADO = 'PREPARADO' AND e2.IDFK = e.ID)


										

INSERT INTO hr.RECEPTOR (EVENTO, ID_EMISOR, SALDO)
SELECT 'LISTO' AS EVENTO , e.ID, (SUM(e.SALDO) + SUM(e2.SALDO)) AS SALDO 
FROM hr.EMISOR e 
JOIN hr.EMISOR2 e2 ON e.ID = e2.ID_EMISOR
WHERE e.EVENTO = 'REALIZAR' AND e2.ESTADO = 'ENVIAR'
GROUP BY e.ID




















										
							   
							   
							   
